version: "3.8"

services:
  api_myccet_infyfix_com_postgres:
    image: postgres:latest
    container_name: api.myccet.infyfix.com.postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data

  api_myccet_infyfix_com_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: api.myccet.infyfix.com
    container_name: api.myccet.infyfix.com
    depends_on:
      - api_myccet_infyfix_com_postgres
    working_dir: /app
    ports:
      - "3007:8000"
    expose:
      - "8000"
    command: sh -c "npm run db:migrate && npm start"
    env_file:
      - ".env"
    environment:
      NODE_ENV: production
      POSTGRES_HOST: api_myccet_infyfix_com_postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      INSTITUTE_DOMAIN: ${INSTITUTE_DOMAIN}
volumes:
  psql_volume_bp:
